### ISSUE TITLE
llvm-config symlink is broken (for the LLVM 4.0.0 copr)

### ISSUE THREAD

**Issue by roboguy13** [da-x/llvm-srpm#1]
I'm trying to install LLVM-4.0.0 from this copr, but `/opt/llvm-4.0.0/bin/llvm-config` ends up symlinked to `llvm-config-64`, which doesn't seem to exist.

**Comment by da-x** [comment]
Check whether `llvm-4.0.0-devel` is installed - you probably need that package for what you're doing. Originally both `llvm-config-64` and its `llvm-config` symlink should have belong there. Sorry for the confusion.

**Comment by roboguy13** [comment]
@da-x That fixed it. Thanks!
