### ISSUE TITLE
Add libomp

### ISSUE THREAD

**Issue by dawagner** [da-x/llvm-srpm#3]
Hi,

First of all, thanks for packaging recent LLVM&co packages for F25 and F26!

I am trying to add libomp as well; I imported the recipe from F28 here: https://github.com/EasyMile/llvm-srpm/tree/libomp-5.0.0 (of course, github won't let me create a pull request for a branch that doesn't exists).
It is different from your own recipes - I tried making it more similar to yours but I don't fully understand how they work, in particular how the sources are retrieved (the Source0 URL doesn't seem to exist for real). I am 100% new to RPM packaging, btw.

**Comment by da-x** [comment]
Hi,

Good work!

I took your changes, added some fixes, added support for CentOS 6, and now it can be shortly tested from the [work-in-progress project](https://copr.fedorainfracloud.org/coprs/alonid/wip) (temporary URL!), staging for LLVM 5.0.1.

I am waiting for the official announcement of LLVM 5.0.1 so I can officially release my RPM builds of LLVM 5.0.1, and our combined work will include a `libomp-5.0.1` RPM. I'll update this Github repository when it happens.

**Comment by da-x** [comment]
(You can see the changes I've made here - https://github.com/da-x/llvm-srpm/commits/libomp-5.0.1)

**Comment by dawagner** [comment]
Awesome, thanks a lot :)

I'm still at loss as to how you generate the packages: looking at https://copr.fedorainfracloud.org/coprs/alonid/wip/build/684809/ for instance, I can see that the source for the build is "SRPM or .spec file upload". When I try to build the packages myself using the "SCM" method, it fails  (e.g. https://copr-be.cloud.fedoraproject.org/results/deubeuliou/llvm-5.0.0/srpm-builds/00684716/builder-live.log or https://copr.fedorainfracloud.org/coprs/deubeuliou/llvm-5.0.0/build/684978/)

**Comment by da-x** [comment]
I use `fedpkg` to generate the SRPM and `copr-cli` to uploading and build it.

**Comment by dawagner** [comment]
Everything from your `wip` repository works fine for me so far.

**Comment by da-x** [comment]
Builds for 5.0.1 are ready.
